# Webserver Config

## The port the webserver will run on
port: 3000

## The title that will be displayed in the top of the menu
title: "OpenWebControl"

## The password to get in the Admin panel
password: "change-me"