# Pterodactyl config

## The url of your pterodactyl instance (no '/' at the end)
url: 'https://pterodactyl.openwebcontrol.com'

## The pterodactyl application key
application_key: ''

## The pterodactyl client key
client_key: ''